### ISSUE TITLE
Randomize options

### ISSUE THREAD

**Issue by dennisschoenmakers** [quintel/etmobile#2]
Currently the choice is between a fixed A and B and only the order if randomised, but my brain would have to work a lot harder is it is (even) more random.

**Comment by antw** [comment]
To be clear, do you mean to randomise the order of questions, or to randomise the order of the *choices* you can make for each question?

**Comment by dennisschoenmakers** [comment]
> To be clear, do you mean to randomise the order of questions, or to randomise the order of the choices you can make for each question?

I meant *both*.

### so right now its:

```
Screen 1
- option A
- option B

Screen 2
- option C
- option D
```

next time it can be:

```
Screen 1
- option C
- option D

Screen 2
- option A
- option B
```

### The (in this issue) proposed change:

```
Screen 1
- option A
- option B

Screen 2
- option C
- option D
```

and then:

```
Screen 1
- option C
- option A

Screen 2
- option B
- option D
```

**Comment by antw** [comment]
@dennisschoenmakers I have pushed this [to the **random-choices** branch](https://github.com/quintel/etmobile/tree/random-choices) and updated [the documentation for adding new choices](https://github.com/quintel/etmobile/tree/random-choices#adding-updating-and-removing-questions).

I haven't merged it into **master** yet, because I'm not convinced this is the right approach. While randomly selecting choices means that a visitor may never see the same question twice, it also means that questions may present users with a false equivalency (i.e. two things they would never have to choose between in the real-world), and we lose the ability to educate. Here's an example:

![screen shot 2016-11-22 at 14 36 29](https://cloud.githubusercontent.com/assets/4383/20529483/32c57f36-b0c8-11e6-8800-e993a1531275.png)

The correct answer (surprisingly) is to swap your car for a train, rather than to swap incandescent light bulbs for LEDs; and yet LED light bulbs are a relatively inexpensive and easy way to reduce your personal CO<sub>2</sub> emissions. LES bulbs reduce emissions by about 1%; which is not huge, but it is an incredibly easy change to make. Since choices in ETMobile are binary (one is correct, one is not), do we not risk dissuading people from taking a very simple, but beneficial action?

I don't think we can reasonably expect visitors to choose between installing household CHPs and using green gas, or between P2P batteries and the balance of heating technologies in refineries.

On the other hand, a question between household CHPs and heat-pumps may well influence someone into making a better decision when their current boiler breaks down. A choice between wind turbines and nuclear – or gas and nuclear – may similarly influence opinions (interestingly, the ETM says nuclear is cleaner than wind: +7.7% vs +5.8% emissions).

I think a smaller number of explicit questions might have a beneficial impact – even if only on a small number of people – and gives us an opportunity to educate. Random choices turns ETMobile into a game of chance. 😞

**Comment by dennisschoenmakers** [comment]
Excellent write up! 😃 :+1: I think this choice is exactly what I would like to discuss next Friday at my meeting with the client. Both have advantages and disadvantages.

With totally random options, it's more of a quiz. What has a bigger impact? 

No, about your example...

> The correct answer (surprisingly) is to swap your car for a train, rather than to swap incandescent light bulbs for LEDs; and yet LED light bulbs are a relatively inexpensive and easy way to reduce your  personal CO2 emissions. LES bulbs reduce emissions by about 1%; which is not huge, but it is an incredibly easy change to make. Since choices in ETMobile are binary (one is correct, one is not), 

This example demonstrates that random choices actually serve a purpose IMO. You will [**learn**](https://media.giphy.com/media/l0MYMlC87bFwYKEdG/giphy.gif) from this that switching (just!) 5% of personal transportation to trains has a bigger impact than switching (all!) the lights from incandescent to LED. 

Furthermore: If we would supply only our *own* predefined choices, changes are high that they are all 'safe' choices and the 'game' will be biased and boring.

Well, let me test the random thing first myself and try it myself. It might be an idea to randomize options **in** sectors. But then again: you'll might learn from total random choices that changes in one sector have a lot more impact than in other sectors. :smile:
