### ISSUE TITLE
Results page should be formulated positively

### ISSUE THREAD

**Issue by dennisschoenmakers** [quintel/etmobile#21]
Right now it reads: 

> Oops! Sorry that was the wrong choice.

That's a downer. We could turn it into an achievement:

**You've answered 4 questions correctly in a row!**

**Comment by antw** [comment]
> That's a downer. We could turn it into an achievement:

Agree.

It would be good to consider what we want the results page to be, other than to show how many correct choices were made.

* Should we show the leaderboard? (I think so)
* Should we show a scenario summary? (e.g. CO<sub>2</sub>: -18.4%). There's a static placeholder for this (and costs) already.
* Should we show a list of correct choices made by the visitor, so that they can review what they did? This might be an opportunity to (re-)read the description texts and learn something.

We might also put the client logo at the bottom of this page?

**Comment by dennisschoenmakers** [comment]
> Should we show the leaderboard? (I think so)

Yes!

> Should we show a scenario summary? (e.g. CO<sub>2</sub>: -18.4%). There's a static placeholder for this (and costs) already.

Kinda dangerous with the current implementation. You cannot just add CO2-reductions, that's faulty.

> Should we show a list of correct choices made by the visitor, so that they can review what they did? This might be an opportunity to (re-)read the description texts and learn something.

Very good idea!

> We might also put the client logo at the bottom of this page?

Arggg overload of good ideas 😜

**Comment by antw** [comment]
Completed with e199af6.

**Comment by dennisschoenmakers** [comment]
We still got a 'oops', which is a bit negative IMO:

![image](https://cloud.githubusercontent.com/assets/104830/22306910/6142dede-e341-11e6-8055-51cd1fca763e.png)
