### ISSUE TITLE
Leaderboard, leaderboard, leaderboard!

### ISSUE THREAD

**Issue by dennisschoenmakers** [quintel/etmobile#22]
An important next step to make this cool.

The leaderboard has two functions:

1. We need to be able to view the leaderboard from your mobile phone. ("how well did I do?")
2. A teacher should be able to put the leaderboard on a beamer / big screen and follow **live** how people are scoring

Of course, it is crucial that people are able to enter their names. 

Also, we need to filter by the following:
* 'Currently' active players
* Players within close proximity (remember that class room!)

**Comment by dennisschoenmakers** [comment]
Perhaps it's good to introduce the concept of a 'game'?

It has the following characteristics:

* A teacher starts a game (e.g. 'Class 6VWO') and can set some characteristics such as: try to get to level 5/6/7
* Pupils that go to to etmobile.nl can 'join' a game
* App aks for name if not already given before

**Comment by antw** [comment]
The leaderboard should rank players based on how many correct choices were made in a row.

Ideally, it should adapt to the level of activity on the website. During busy periods it might show only results from the past 24-hours, but in quiet periods it would include results from the past seven days or even as far back as a month. This will ensure that the leaderboard never looks empty, but also means older high scores drop off the leaderboard and don't dominate the top spots forever.

### Storing results

Currently ETMobile is a pure client-side project and has no server whatsoever. That must change if we are to persist game results.

I think the first port-of-call should be to look into [Google's Firebase](https://firebase.google.com/), a hosted real-time database designed with JavaScript apps in mind, which [would surely be free](https://firebase.google.com/pricing/) at ETMobile's scale. This would prevent the additional complexity of deploying our own server application for a simple feature.

As a real-time database, it also means the leaderboard could update automatically as new results come in.

If this doesn't work, we would likely have to create a server application to do it. I would like to avoid this *if we can* because the solutions for combining Rails and React *in one application* [are rather "clunky"](https://github.com/shakacode/react_on_rails). We would probably end up with two application: ETMobile frontend (this repo) and ETMobile server (a Rails::API app?).

### "Games" and location

> Perhaps it's good to introduce the concept of a 'game'?

There are two possibilities:

1. Have a teacher / conference leader create a game which people can join. The leaderboard can then be scoped to those participating in the game, and there is no need for older scores to drop-off the leaderboard.

2. Detect the visitor's location and create a "players near you" leaderboard.

I prefer (1) – at least for this first version – since (2) has the following drawbacks:

* We must prompt visitors to share their location with us; this adds an extra barrier before playing, and may discourage privacy-minded persons from playing.
* Storing location data comes with privacy and data protection concerns. This is doubly important if there are kids playing.

(1) avoids both of these problems at the cost of an additional step to create the game.

### Visitor names

> it is crucial that people are able to enter their names [...] App asks for name if not already given before

I think the ideal approach would be [similar to ETFlex](http://light.energytransitionmodel.com/scenes/1) whereby you can start playing without entering any information (with the results attributed to "Anonymous"), and then ask the visitor for a name the first time they get a question wrong.

This does raise the risk of a leaderboard full of "Anonymous", but I think it's worth it to get visitors into the game faster.

When the visitor is playing a game made by a teacher, we might ask for the name *before* starting since those visitors are likely to continue playing anyway.

### Global leaderboard

If we add a game- or location-based leaderboard, I still think we should have a global leaderboard which aggregates all scores (and should adapt to busy and quiet periods as described in the second paragraph). It should also be possible for visitors to play without joining a game, e.g. a "random" visitor who isn't part of any classroom or conference.
