### ISSUE TITLE
How is TravelByTrain translated into slider setting?

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmobile#64]
The slider-setting related to this choice is: transport_useful_demand_car_kms: -0.15

How does that relate to 

```
      People spent a lot of energy driving around in cars. What if we managed
      to convice 5% (more) to use the train instead of a car? This will save energy,
      CO<sub>2</sub> emissions, costs and shorten traffic jams!
    ```

**Comment by dennisschoenmakers** [comment]
-0.15 per annum amounts to -5% in total. We assume we can fit 5% more people in the same trains.

![image](https://cloud.githubusercontent.com/assets/104830/22365872/23545d3e-e47a-11e6-8982-a2b3453b1ec9.png)

**Comment by antw** [comment]
I think @ChaelKruip means that reducing car journeys by 5% and increasing train journeys by 5% aren't equivalent, since there is far more demand for "car energy" ([119.26 PJ](https://beta-engine.energytransitionmodel.com/data/630081/converters/transport_useful_demand_car_kms)) than "train energy" ([5.89 PJ](https://beta-engine.energytransitionmodel.com/data/630081/converters/transport_useful_demand_trains))

@ChaelKruip: This was one of the earliest choices I added, mostly for demonstration purposes. I'm not sure how we could alter this input since the ETM doesn't really have the concept of a journey. A 5% decrease in energy used by cars is a 100%% increase in energy used by trains (but perhaps trains are more efficient per passenger kilometre?).

**Comment by ChaelKruip** [comment]
> -0.15 per annum amounts to -5% in total. We assume we can fit 5% more people in the same trains.

OK, that seems not too crazy as long as it is not during rush-hour. 

> I'm not sure how we could alter this input since the ETM doesn't really have the concept of a journey. A 5% decrease in energy used by cars is a 100%% increase in energy used by trains (but perhaps trains are more efficient per passenger kilometre?).

Ok, thanks. I think @dennisschoenmakers means that it is assumed that no extra train-km are needed but just fewer car-kms can be realised. Fair enough.

**Comment by dennisschoenmakers** [comment]
> I think @dennisschoenmakers means that it is assumed that no extra train-km are needed but just fewer car-kms can be realised. Fair enough.

A big thumbs up 👍  👍  from these guys:

![image](https://cloud.githubusercontent.com/assets/104830/22376524/b418bda4-e4ae-11e6-8632-1fe1f7ac208e.png)
